# docker run --rm -d -e POSTGRES_PASSWORD=password postgres:17

# docker run --rm --pull always -e DATABASE_URL_TEST=jdbc -v "m2:/root/.m2" -v "$(pwd):/app" -w /app maven:3.9.5-amazoncorretto-17 mvn -Ptestdb clean integration-test

services:

  testjava:
    image: maven:3.9.5-amazoncorretto-17
    environment:
      DATABASE_URL_TEST: jdbc://postgresdb:5432/database
    volumes:
      - "m2:/root/.m2"
      - "/home/gael/Projects/argonaultes/tmp-projects/trde512-ds-2025-2026/rest-service/:/app"
    working_dir: /app
    command: mvn -Ptestdb clean integration-test
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: password

volumes:
  m2: